"""empty message

Revision ID: 61dfb820c37f
Revises: 891dc305a4b8
Create Date: 2024-03-25 07:55:58.984736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dfb820c37f'
down_revision = '891dc305a4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_media', sa.String(length=255), nullable=True))
        batch_op.drop_column('post_video_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_video_link', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('post_media')

    # ### end Alembic commands ###
