"""empty message

Revision ID: 891dc305a4b8
Revises: 6bc728413a13
Create Date: 2024-03-25 07:44:17.545666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891dc305a4b8'
down_revision = '6bc728413a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.alter_column('post_video_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post_video_link',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
